##### Menu
menu:
  主页: /
  归档: /archives
  关于: /about

## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- links
- tag
#- github-card
- category
#- douban
#- rss
#- weibo
  ## provide eight widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo

#### RSS 
#rss: /atom.xml ## RSS address.


#### Image
imglogo:
  enable: true
  src: img/logo.png
favicon: img/favicon.ico  
apple_icon: img/idev.png
author_img: 
banner_img: #img/other

### Theme Color 
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

# 代码高亮主题
# available: default | night
highlight_theme: default

#### index post is expanding or not 
index:
  expand: false           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: Read More  

close_aside: true  #close sidebar in post page if true
mathjax: false      #enable mathjax if true

### Creative Commons License Support, see http://creativecommons.org/ 
### you can choose: by , by-nc , by-nc-nd , by-nc-sa , by-nd , by-sa , zero
creative_commons: none

#### Author information
author:
  intro_line1: 
  weibo: 
  weibo_verifier: 
  tsina: 
  stackoverflow: 
  douban:	
  zhihu: 
  email: 
  twitter: 
  github: 
  facebook:
  linkedin:
  google_plus:

#### Toc
toc:
  article: true   ## show contents in article.
  aside: false     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links

links:
  <div style="width:100%; text-align:left; margin-top:12px; margin-bottom:10px;">App<div/> : javascript:void(0)
  <img id="img" onmouseover="change(this);" onmouseleave="leave(this);" src="http://idevnotes.com/img_blog/reader.png" />: http://www.smartisan.com/apps/reader
  <div style="width:100%; text-align:left; margin-top:26px; margin-bottom:12px;">Podcast<div/> : javascript:void(0)
  <img id="img" onmouseover="change(this);" onmouseleave="leave(this);" src="http://idevnotes.com/img_blog/banlanshow.png" />: https://banlan.show/bitvoice
  <div style="width:100%; text-align:left; margin-top:25px; margin-bottom:10px;">VPN</div> : javascript:void(0)
  <img id="img" onmouseover="change(this);" onmouseleave="leave(this);" src="http://idevnotes.com/img_blog/duotai.png" />: https://duotai.org
  <img id="img" onmouseover="change(this);" onmouseleave="leave(this);" src="http://idevnotes.com/img_blog/vpnso.png" />: https://www.vpnso.com/main.php
  <img id="img" onmouseover="change(this);" onmouseleave="leave(this);" src="http://idevnotes.com/img_blog/eurekavpt.png" />: https://eurekavpt.com
#### Comment
duoshuo_shortname:    ## e.g. idev your duoshuo short name.
##disqus_shortname: idev    ## e.g. idev your disqus short name.

donate:
  enable: false
  text: 
  wechat: 
  alipay: 
  web: false

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:  ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176284895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: true
  id:    ## e.g. UA-46421946-2 your google analytics ID.
  site:      ## e.g. idevnotes.com your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: true
  sitecode:   ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code

cnzz_tongji:
  enable: false
  siteid:   ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search

swift_search:
  enable: false

google_cse: 
  enable: true
  cx:   ## e.g. 018294693175868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id: ## e.g. "783281470518440642"  for your baidu search id
  site:   ## your can change to your site instead of the default site
  
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
